// Re-export all types from shared package for backwards compatibility
export {
  // Enums
  NoteType,
  BinderCategory,
  Visibility,
  DishCategory,
  PortionSize,
  WineType,
  WineFinish,
  SpiritType,
  ServingMethod,
  PurchaseContext,
  TasteSignalType,
  TasteCategory,
  SubscriptionTier,
  // Models
  type User,
  type PublicUser,
  type Binder,
  type PublicBinder,
  type Photo,
  type Venue,
  type Note,
  type SocialNote,
  type Tag,
  type TasteSimilarity,
  type GourmetFriend,
  type TasteSignal,
  type TasteSignalSummary,
  type UserSuggestion,
  type PublicProfile,
  type CanPinResult,
  type TieredSearchResult,
  // Extensions
  type RestaurantExtension,
  type WineExtension,
  type SpiritExtension,
  type WineryVisitExtension,
  // API Response
  type ApiResponse,
  type PaginatedResponse,
  type PresignResponse,
  type SearchResult,
  // Phase 3
  type SubscriptionStatus,
  type MenuDeciderDish,
  type MenuDeciderResponse,
  type MapPin,
  type NotificationPreferences,
  type PioneerBadge,
  type PioneerZone,
} from '@mygourmetdiary/shared-types';
